### ISSUE TITLE
3.x TODO List

### ISSUE THREAD

**Issue by shawncplus** [RanvierMUD/ranviermud#375]
# For 3.x Release

## Core

- [x] Attributes refactor (merged into npmified)
- [x] Area scriptability (#373 / https://github.com/RanvierMUD/core/pull/4)
- [x] CommandParser/Room exits refactor
- [x] Data layer refactor

## Docs

- [x] Move docs from core into its own repo
- [x] Setup docs build runway
- [x] Update docs with attributes updates (including computed attributes)
- [x] Update docs with Entity Loaders
- [x] Update docs with area scripting

## Bundles

- [x] Move waypoint, recall commands to their own bundle
- [x] Move `talk` command (`bundle-example-commands`) and sentient behavior (`bundle-example-npc-behaviors`) into one combined dialogflow bundle, right now they're both polluting other bundles
- [x] Remove 'example' name from example bundles that can really stand on their own: crafting, npc-behaviors, telnet, websocket, vendor, groups

# Post-release

## Example Bundles

* Add some kind of NPC pathing behavior to `npc-behaviors` bundle

## Soma

Really just needs a full once-over. It barely works right now
